name: "Release"

on:
  push:
    branches:
      - "master"

jobs:
  release:
    name: "Build artifacts and release"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Perform unit tests
        run: gradle test
      - name: Build
        run:
          gradle build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"